feat(backend): mount EmptyDir volumes for launcher write locations
kubeflow/pipelines pull request #10538
Opened 2024-03-04 21:49 UTC by gregsheremeta

Launcher writes input artifacts to root paths `/gcs`, `/minio`, and `/s3`. These paths are not accessible by non-root users by default, which is problematic in locked-down Kubernetes installations and/or OpenShift. [`/gcs` is currently a contract for KFP v2 python component wrappers, so the path cannot be changed.](https://github.com/kubeflow/pipelines/issues/5673#issuecomment-901045901)

Mount an EmptyDir scratch volume to these paths to work around this.

Additionally, `/.local` and `/.cache` are written to by pip, so add EmptyDir mounts for those too.

Fixes: #5673
Fixes: #7345

2024-03-04 22:32 UTC, Tomcli reviewed
Thanks @gregsheremeta, just wondering is there anyway we can reduce the amount of the volume mount definition? Due to the k8s yaml size limitation, we won't able to fit more tasks if the individual container definition is too big.

2024-03-04 23:02 UTC, Tomcli commented
/ok-to-test

2024-03-04 23:03 UTC, Tomcli requested changes
@gregsheremeta You also need to update the unit tests because you modified the container spec in this PR.

2024-04-14 11:28 UTC, andraxin commented
This will not solve the `Permission denied` error reported in https://github.com/kubeflow/pipelines/issues/10397,
unless a version of the v2 launcher that includes [this fix](https://github.com/kubeflow/pipelines/commit/4003e562713bd04fa94387d8b53dfbe3cf31cb12) is used.

_**BTW: where/how do I tell Kubeflow which launcher image to use?**_

That's because the root cause for the original error is that the installer creates
(or used to create, after the fix)   directories with mode `0644`, i.e. `drw-r--r--`,
which makes it impossible for unprivileged users to create subdirectories within,
but doesn't hamper `root`...

### Brief Demo
```console
$ docker run --rm -it alpine
/ # adduser -D demo
/ # su - demo
05decfa077fd:~$ mkdir -m 0644 demo
05decfa077fd:~$ mkdir demo/test
mkdir: can't create directory 'demo/test': Permission denied
05decfa077fd:~$ 
/ # mkdir /home/demo/demo/test
/ # ls -lR /home/demo
/home/demo:
total 4
drw-r--r--    3 demo     demo          4096 Apr 14 11:16 demo

/home/demo/demo:
total 4
drwxr-xr-x    2 root     root          4096 Apr 14 11:16 test

/home/demo/demo/test:
total 0
/ # 
```

BTW, that also explains why creating alternate images with world-read-write
`/minio` pre-created (i.e. `RUN mkdir -m 1777 /minio`) doesn't help.

I tracked this down by [mounting a PVC](https://kfp-kubernetes.readthedocs.io/en/kfp-kubernetes-1.0.0/source/kubernetes.html#kfp.kubernetes.mount_pvc) at `/minio` and observing permissions
on the first level (that does get created).

2024-04-15 20:07 UTC, rimolive commented
> unless a version of the v2 launcher that includes [this fix](https://github.com/kubeflow/pipelines/commit/4003e562713bd04fa94387d8b53dfbe3cf31cb12) is used.

This fix was introduced in KFP 2.0.2

2024-04-16 23:25 UTC, andraxin commented
> > unless a version of the v2 launcher that includes [this fix](https://github.com/kubeflow/pipelines/commit/4003e562713bd04fa94387d8b53dfbe3cf31cb12) is used.
> 
> This fix was introduced in KFP 2.0.2

Yes, I'm well aware. GitHub shows that quite prominently.
```
fix(backend): OutPutPath dir creation mode Fixes https://github.com/kubeflow/pipelines/issues/7629 (https://github.com/kubeflow/pipelines/pull/9946)
[master](https://github.com/kubeflow/pipelines) ([#9946](https://github.com/kubeflow/pipelines/pull/9946))
[sdk-2.7.0](https://github.com/kubeflow/pipelines/releases/tag/sdk-2.7.0)
[2.0.2](https://github.com/kubeflow/pipelines/releases/tag/2.0.2)
```

BUT, that doesn't really help me or answer my question.
The launcher that's spawned by default in the Kubeflow v1.7.x
deployment I **have to** use apparently pre-dates that; and,
I have no idea how/if Kubeflow can be instructed to grab
a newer launcher with the fix.

2024-04-17 01:17 UTC, rimolive commented
Kubeflow 1.7 comes with an alpha release of KFP. You should either fully upgrade your kubeflow installation to 1.8 or you can upgrade individually kfp. Just a reminder that if you choose the later one, you need to use the multi-user manifests, as you probably deployment Kubeflow w/ multi-user support.

2024-04-17 02:08 UTC, andraxin commented
> Kubeflow 1.7 comes with an alpha release of KFP. You should either fully upgrade your kubeflow installation to 1.8 or you can upgrade individually kfp. Just a reminder that if you choose the later one, you need to use the multi-user manifests, as you probably deployment Kubeflow w/ multi-user support.

I guess I wasn't sufficiently clear, when I said I **have to** use Kubeflow 1.7.
I cannot upgrade the installation nor apply any manifests at the cluster level.
Applying manifest in my profile's namespace is about as far as I can reach.

My re-stated question becomes: as a Kubeflow **user**, can I somehow instruct
Kubeflow to use a newer launcher image to run my pipelines?

BTW, I _can_ use custom images for my pipeline stages with world-read-write
`/gcs`, `/minio`, and `/s3`, which renders these emptyDir volume mounts moot.
**If** I could only tell Kubeflow to use a launcher with the fix, that is.

2024-04-17 11:11 UTC, rimolive commented
> My re-stated question becomes: as a Kubeflow user, can I somehow instruct
Kubeflow to use a newer launcher image to run my pipelines?

If, and only if, you upgrade your KFP installation to at least 2.0.5 release, you can [parametrize the launcher and driver images](https://github.com/kubeflow/pipelines/commit/23a2bc3ba370e28a5ef5f0e0df1e40ec8f7888b9) which include that configuration.

2024-04-17 17:10 UTC, andraxin commented
> > My re-stated question becomes: as a Kubeflow user, can I somehow instruct
> > Kubeflow to use a newer launcher image to run my pipelines?
> 
> If, and only if, you upgrade your KFP installation to at least 2.0.5 release, you can [parametrize the launcher and driver images](https://github.com/kubeflow/pipelines/commit/23a2bc3ba370e28a5ef5f0e0df1e40ec8f7888b9).

I see.  Thanks for the info, and your patience! :smirk: 

Given that the code changes you linked appear to be
in backend Golang code, what you call "KFP installation"
probably includes more than just `pip install kfp==2.0.2`
inside a notebook in the existing Kubeflow 1.7 cluster.
Is that correct?

2024-04-17 17:38 UTC, rimolive commented
Yes, this is not a simple SDK upgrade or code changes. You will need to upgrade your whole KFP installation.

2024-05-29 20:35 UTC, thesuperzapper commented
@chensun @HumairAK @Tomcli we definitely need to prioritize fixing this issue, because it's pretty bad to have a hard requirement on root container images, see https://github.com/kubeflow/pipelines/issues/10397 for an example of user having this problem.

2024-05-30 19:47 UTC, droctothorpe commented
FYI: https://github.com/kubeflow/pipelines/issues/10397#issuecomment-2140756532

2024-05-31 19:06 UTC, HumairAK commented
@gregsheremeta  is currently out, 

due to the expressed urgency and prioritzation of this, I'm picking this PR up here: https://github.com/kubeflow/pipelines/pull/10857

please forward any further discussions to the pr above

/close

2024-05-31 19:06 UTC, closed without merging