Drop GCPC Python 3.7 part 1
kubeflow/pipelines pull request #10750
Opened 2024-04-25 01:17 UTC by rickyxie0929

**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2024-04-25 18:42 UTC, rickyxie0929 commented
/retest

2024-04-29 19:17 UTC, rickyxie0929 commented
/retest-required

2024-04-29 23:33 UTC, rickyxie0929 commented
/restest

2024-04-30 01:16 UTC, rickyxie0929 commented
/retest-required

2024-04-30 20:28 UTC, rickyxie0929 commented
/test kubeflow-pipelines-sdk-execution-tests

2024-05-01 15:37 UTC, connor-mccarthy requested changes
I think the title of this PR is out-of-date since the changes are for the KFP SDK rather than GCPC SDK. Can we also use the [Pull Request Title Convention](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention)?

2024-05-01 15:37 UTC, connor-mccarthy commented on sdk/RELEASE.md
> +* Drop support for Python 3.7 since it has reached end-of-life. [\#10734](https://github.com/kubeflow/pipelines/pull/10734)
Number is stale

2024-05-01 23:21 UTC, rickyxie0929 commented
/test kubeflow-pipelines-sdk-execution-tests

2024-05-02 18:14 UTC, chensun commented on sdk/RELEASE.md
> +* Drop support for Python 3.7 since it has reached end-of-life(part1). [\#10750](https://github.com/kubeflow/pipelines/pull/10750)
I think this should be considered as a breaking change. Other than that, the change looks good to me.

2024-05-02 18:33 UTC, connor-mccarthy requested changes
What is part 2 of this PR? I see the title says "(part 1)".

2024-05-02 22:50 UTC, connor-mccarthy requested changes

2024-05-02 22:50 UTC, connor-mccarthy commented on sdk/RELEASE.md
> +* Drop support for Python 3.7 since it has reached end-of-life(part1). [\#10750](https://github.com/kubeflow/pipelines/pull/10750)
We can remove part1 from the change description

2024-05-03 18:23 UTC, chensun approved these changes
/lgtm
/approve

Thanks!

2024-05-03 18:51 UTC, rickyxie0929 commented
/retest-required

2024-05-03 19:11 UTC, merged