fix(SDK): Update kubernetes.use_secret_as_env to accept secret name dynamically at runtime
kubeflow/pipelines pull request #11121
Opened 2024-08-20 23:09 UTC by DharmitD

**Description of your changes:**
Resolves https://github.com/kubeflow/pipelines/issues/10914 
Similar to https://github.com/kubeflow/pipelines/pull/11039 

- Updated SDK DSL compile code to have the secret_name accepted as a `PipelineParameterChannel` type this way:
```
@dsl.component(base_image=<base_image>)
def print_secret():
    import os
    # print(os.environ['SECRET_VAR'])

@dsl.pipeline
def pipeline(secret_name: str):
    task = print_secret()
    kubernetes.use_secret_as_env(task,
                                 secret_name=secret_name,
                                 secret_key_to_env={'password': 'SECRET_VAR'})
```
- Implemented support for dynamically specifying secret names in the `use_secret_as_volume` function.
- Updated driver code to handle secret name substitution at runtime based on input parameters.
- Introduced a `{{secret_name}}` template string representation for secret names in the compiled DSL.
- Added a test to validate secret name template creation in IR.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2024-08-21 01:09 UTC, DharmitD commented
@chensun updates same as that in https://github.com/kubeflow/pipelines/pull/11039 
Could you please take a look at both PRs and let us know if this approach works? Thank you!

2024-08-21 15:37 UTC, VaniHaripriya commented
Looks good to me.

2024-08-23 22:04 UTC, DharmitD commented
@chensun bumping :)

cc: @gregsheremeta @rimolive

2024-09-06 17:34 UTC, chensun requested changes
Same comment as https://github.com/kubeflow/pipelines/pull/11039/files#r1747488744

2024-12-31 07:41 UTC, closed without merging