test: Move run-all-gcpc-modules to GitHub Actions
kubeflow/pipelines pull request #11157
Opened 2024-08-31 00:03 UTC by aman23bedi

**Description of your changes:**
Moved `run-all-gcpc-modules` test to github actions. 

Resolves: 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2024-08-31 00:09 UTC, aman23bedi commented
@hbelmiro

2024-08-31 15:23 UTC, hbelmiro commented
/ok-to-test
/rerun-all

2024-09-02 12:15 UTC, hbelmiro commented
/ok-to-test
/rerun-all

2024-09-02 12:55 UTC, hbelmiro approved these changes
/lgtm

Thank you for working on this @aman23bedi.

Don't forget to remove the existing Prow configuration from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Once removed, please rebase this PR so the Prow test doesn't block the merge.

2024-09-02 12:59 UTC, diegolovison requested changes

2024-09-02 12:59 UTC, diegolovison commented on .github/workflows/gcpc-modules-tests.yml
> +          python-version: 3.8
Move to python 3.9

2024-09-02 16:22 UTC, diegolovison commented
/lgtm

2024-09-02 18:22 UTC, hbelmiro commented
/ok-to-test
/rerun-all

2024-09-02 18:24 UTC, hbelmiro commented
/ok-to-test
/rerun-all

2024-09-02 19:02 UTC, hbelmiro commented
/unhold

2024-09-04 14:00 UTC, hbelmiro commented
@aman23bedi can you please add a link to https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2362 in the [description of this PR](https://github.com/kubeflow/pipelines/pull/11157#issue-2498448958) so we can quickly find it?
You can use https://github.com/kubeflow/pipelines/pull/10926#issue-2360648987 as a reference.

2024-09-06 17:08 UTC, hbelmiro commented
/retest

2024-09-06 17:16 UTC, hbelmiro commented
`test-run-all-gcpc-modules` is expected to fail because the script it invokes was removed.

2024-09-06 19:38 UTC, hbelmiro commented
@aman23bedi https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2362 was merged.
Can you please squash your commits and rebase?

cc @DharmitD

2024-09-06 20:53 UTC, chensun commented
> @aman23bedi [GoogleCloudPlatform/oss-test-infra#2362](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2362) was merged. Can you please squash your commits and rebase?
> 
> cc @DharmitD

I can simply merge this manually.

2024-09-06 20:53 UTC, merged