chore(backend): remove usage of deprecated commonLabels in Kustomize manifests
kubeflow/pipelines pull request #11289
Opened 2024-10-12 12:58 UTC by etheleon

**Description of your changes:**

Removed commonLabels since it's deprecated in Kustomize's [api/v0.16.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.16.0) release. In it's place labels and selectors should be mentioned explicitly in the resource.

**Checklist:**
- [x ] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2024-10-12 12:59 UTC, etheleon commented
resolves #11272

2024-10-16 05:17 UTC, etheleon commented
running `grep -r "commonLabels"` does not return any file

2024-10-16 05:25 UTC, etheleon commented
/verify-owners

2024-10-16 12:50 UTC, hbelmiro commented
/ok-to-test
/rerun-all

2024-10-16 22:08 UTC, DharmitD commented
@HumairAK could you approve the workflow runs? ty!

2024-10-16 22:09 UTC, DharmitD commented on manifests/kustomize/base/installs/generic/postgres/postgres-secret-extended.yaml
> +  password: "password"
Make sure to fix EoF here :)

2024-10-17 13:28 UTC, hbelmiro commented
/ok-to-test
/rerun-all

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/env/dev/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/env/dev/postgresql/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/env/gcp/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/env/plain-multi-user/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-17 18:23 UTC, hbelmiro commented on manifests/kustomize/sample/kustomization.yaml
>  # when application is deleted.
This comment got misplaced.

2024-10-22 03:44 UTC, etheleon commented on manifests/kustomize/env/dev/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:44 UTC, etheleon commented on manifests/kustomize/env/dev/postgresql/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:45 UTC, etheleon commented on manifests/kustomize/env/gcp/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:46 UTC, etheleon commented on manifests/kustomize/env/plain-multi-user/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:46 UTC, etheleon commented on manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:46 UTC, etheleon commented on manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:47 UTC, etheleon commented on manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:47 UTC, etheleon commented on manifests/kustomize/sample/kustomization.yaml
>  # when application is deleted.
removed

2024-10-22 03:49 UTC, etheleon commented
hi @hbelmiro I've removed the redundant comments

2024-10-22 12:28 UTC, hbelmiro requested changes
@etheleon can you please sign-off your commits?

2024-10-22 12:28 UTC, hbelmiro commented on manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
>  # when application is deleted.
You forgot to remove this one.

2024-11-01 20:51 UTC, hbelmiro commented
@etheleon did you had the chance to see my comments here?
https://github.com/kubeflow/pipelines/pull/11289#pullrequestreview-2385041256

2024-11-03 01:42 UTC, etheleon commented on manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
>  # when application is deleted.
got it!

2024-11-04 12:35 UTC, hbelmiro reviewed
Thank you @etheleon.
You still need to [sign off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits).

2024-11-05 04:05 UTC, etheleon commented
> Thank you @etheleon. You still need to [sign off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits).

Let me rebase and sign off thanks for reminding

2024-11-06 11:41 UTC, hbelmiro reviewed
/lgtm

cc @HumairAK

2025-01-09 20:18 UTC, HumairAK commented
@etheleon would like to get this into 2.4, do you think you can rebase?

2025-01-13 20:47 UTC, HumairAK requested changes

2025-01-13 20:47 UTC, HumairAK commented on manifests/kustomize/base/postgresql/cache/cache-deployment-patch.yaml
> +  label:
```suggestion
  labels:
```

2025-01-13 20:47 UTC, HumairAK commented on manifests/kustomize/base/postgresql/pipeline/ml-pipeline-apiserver-deployment-patch.yaml
> +  label:
```suggestion
  labels:
```

2025-01-13 20:47 UTC, HumairAK commented on manifests/kustomize/base/postgresql/pipeline/ml-pipeline-apiserver-deployment-patch.yaml
> +      label:
```suggestion
      labels:
```

2025-01-13 20:47 UTC, HumairAK commented on manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
> +    application-crd-id: kubeflow-pipelines
I see there are a couple of instances where you have added the labels manually, may I ask why? why not put this in the kustomization.yaml via: 

```
labels:
- includeSelectors: true
  pairs:
    application-crd-id: kubeflow-pipelines
```

like you have done elsewhere?

2025-01-13 20:47 UTC, HumairAK commented
There are some requested changes, let's move this to kfp 2.5 while we address them.

2025-01-14 15:03 UTC, etheleon commented on manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
> +    application-crd-id: kubeflow-pipelines
hey @HumairAK, initially i was updating the files manually and not using the prescribed method used from `kustomize`

2025-01-15 08:30 UTC, etheleon commented on manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
> +    application-crd-id: kubeflow-pipelines
let me move all the ones i've added manually to `kustomization.yaml`

2025-01-15 12:28 UTC, hbelmiro commented
/ok-to-test

2025-04-08 12:38 UTC, hbelmiro commented
/reopen

2025-04-08 15:49 UTC, HumairAK commented
thank you for this effort, however the pr is now superceded by: https://github.com/kubeflow/pipelines/pull/11733

2025-04-08 15:49 UTC, closed without merging

2025-04-15 03:44 UTC, etheleon commented
Hey @HumairAK, understand it was a better fit. I wished there was more coordination