feat(documentation): Add architecture diagram
kubeflow/pipelines pull request #11490
Opened 2024-12-29 18:14 UTC by anishasthana

Closes #10957

This is a first draft of an architecture diagram for Kubeflow Pipelines. I started with mermaid-js but it was taking a long while... I figured we can get something via draw.io diagram and then iterate over time.

cc @HumairAK

2024-12-30 11:38 UTC, hbelmiro commented on images/kfp-cluster-wide-architecture.png
> <img width="444" alt="Screenshot 2024-12-30 at 08 22 30" src="https://github.com/user-attachments/assets/2a33a097-e268-4276-9aef-272c4b3267ad" />

I think you meant "Note that it **doesn't** contain any metadata".

2024-12-30 11:38 UTC, hbelmiro commented on images/kfp-cluster-wide-architecture.png
> <img width="164" alt="Screenshot 2024-12-30 at 08 27 19" src="https://github.com/user-attachments/assets/19240564-f6d7-4576-9d96-32b60f29c659" />

How about renaming it to `API Server`? That way it will be clearer [what part of the codebase](https://github.com/kubeflow/pipelines/tree/master/backend/src/apiserver) this is.

2024-12-30 11:38 UTC, hbelmiro commented on images/kfp-cluster-wide-architecture.png
> <img width="398" alt="Screenshot 2024-12-30 at 08 32 03" src="https://github.com/user-attachments/assets/a5c56e24-7ee6-4add-9ed4-e0fb3cfcb83d" />

These two "Creates" come from Pipeline Server, right? The diagram doesn't clarify that. Maybe move those lines a bit away from the PA's ones.

2024-12-30 16:29 UTC, anishasthana commented
@hbelmiro thanks for the review. I've made some updates.

2024-12-30 16:37 UTC, hbelmiro reviewed
/lgtm

2025-01-02 15:51 UTC, rimolive requested changes

2025-01-02 15:51 UTC, rimolive commented on README.md
> +[Direct Meeting Link](https://meet.google.com/phd-ixfj-kcr/)
Can you update with the zoom links? 

https://zoom.us/j/92607298595?pwd%3DVlKLUbiguGkbT9oKbaoDmCxrhbRop7.1&sa=D&source=calendar&ust=1736264977415448&usg=AOvVaw1EIkjFsKy0d4yQPptIJS3x

2025-01-02 17:38 UTC, anishasthana commented on README.md
> +[Direct Meeting Link](https://meet.google.com/phd-ixfj-kcr/)
Done!

2025-01-09 17:35 UTC, rimolive commented
/lgtm

2025-01-09 19:57 UTC, Achuth17 commented on README.md
> +We also have a slack channel on the Cloud Native Computing Foundation Slack workspace at [#kubeflow-pipelines](https://cloud-native.slack.com/archives/C073N7BMLB1)
Is it better to link to https://www.kubeflow.org/docs/about/community/#kubeflow-slack-channels instead?

https://cloud-native.slack.com/archives/C073N7BMLB1  or https://kubeflow.slack.com assumes someone is already a member of the slack workspace.

2025-01-10 18:18 UTC, franciscojavierarceo commented
![image](https://github.com/user-attachments/assets/5652593e-85c3-465c-a39c-012c2db40235)

2025-01-10 18:19 UTC, rimolive commented
/lgtm

2025-01-10 21:42 UTC, HumairAK commented on README.md
> +## Architecture
I don't think we should put the arch diagram in the front readme of the repo, can we move this further into the docs folder? https://github.com/kubeflow/pipelines/tree/master/docs

once done we can link it from the kfp website in the operator-guides section: https://www.kubeflow.org/docs/components/pipelines/operator-guides/

2025-01-16 15:44 UTC, HumairAK commented
/lgtm
/approve

2025-01-16 17:50 UTC, anishasthana commented
/retest

2025-01-16 17:55 UTC, VaniHaripriya commented
/lgtm

2025-01-16 17:56 UTC, hbelmiro reviewed
/lgtm

2025-01-16 17:57 UTC, hbelmiro commented
/rerun-all

2025-01-16 18:16 UTC, VaniHaripriya commented on .github/workflows/ci-checks.yml
> +      - uses: actions/upload-artifact@v4.6.0
```suggestion
      - uses: actions/upload-artifact@v4

2025-01-16 20:17 UTC, VaniHaripriya commented
/rerun-all

2025-01-16 20:18 UTC, hbelmiro commented
/close

2025-01-16 20:18 UTC, hbelmiro commented
/reopen

2025-01-16 20:20 UTC, hbelmiro commented
@anishasthana can you please rebase?

2025-01-17 12:40 UTC, hbelmiro approved these changes
/lgtm

2025-01-17 12:42 UTC, merged