fix(components): Print logs for AWS Sagemaker components
kubeflow/pipelines pull request #4879
Opened 2020-12-08 22:26 UTC by akartsky

Add print logs to Batch Transform and Processing

2020-12-08 22:27 UTC, akartsky commented
/area components/aws/sagemaker

2020-12-11 20:18 UTC, RedbackThomson commented
lgtm
/ok-to-test

2020-12-14 19:17 UTC, surajkota commented
I see only processing and transform, do we have logs for others already checked in ?

2020-12-14 19:18 UTC, surajkota commented
Also, is there any quick change we can make to integ tests so this is not missed next time

2021-02-22 20:10 UTC, akartsky commented
> I see only processing and transform, do we have logs for others already checked in ?

we only have logging for training, processing and transform jobs

2021-02-22 20:14 UTC, akartsky commented
> Also, is there any quick change we can make to integ tests so this is not missed next time

added unit test to make sure `_print_cloudwatch_logs` is called 
and we [already have unit tests](https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/tests/unit_tests/tests/common/test_sagemaker_component.py#L268) for `_print_cloudwatch_logs`

2021-02-23 01:17 UTC, surajkota commented
/approve

wait for release changes

2021-02-24 02:36 UTC, surajkota requested changes

2021-02-24 02:36 UTC, surajkota commented on components/aws/sagemaker/Changelog.md
> +**Change log for version 1.1.0**
1.1.1

2021-02-24 02:42 UTC, surajkota approved these changes
/lgtm

2021-02-24 03:19 UTC, merged