fix(components/pytorch) [WIP] Pytorch Lightning Arguments string pass through
kubeflow/pipelines pull request #5870
Opened 2021-06-16 15:02 UTC by shrinath-suresh

The arguments specific to pytorch lightning changes quite frequently. If the variables are hardcoded in the script, whenever there is a release, the script needs to be changed. 

As per the discussion, it is decided to pass the ptl arguments as string input from user script. This PR contains the changes for the same

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2021-06-17 19:20 UTC, jagadeeshi2i requested changes

2021-06-17 19:20 UTC, jagadeeshi2i commented on samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
> +    "    ptl_args = f\"max_epochs={max_epochs}\"\n",
Pls add profiler, gpus and accelerator args.

2021-06-22 06:50 UTC, chauhang commented
/ok-to-test
/lgtm

2021-06-24 05:27 UTC, chauhang approved these changes

2021-06-24 05:28 UTC, chauhang commented
/lgtm
/approved
/ok-to-test

2021-06-24 06:10 UTC, merged