feat(sdk): Support loading pipeline from yaml
kubeflow/pipelines pull request #8209
Opened 2022-08-30 09:43 UTC by chensun

**Description of your changes:**
- Support loading pipeline from yaml to use as a component.
- Fix bug where InputSpec ignores artifacts inputs from IR.
- Fix bug where executor label and component name may not be merged correctly due to name collision.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2022-08-30 10:42 UTC, chensun commented
/test kubeflow-pipelines-samples-v2

2022-08-30 16:46 UTC, zichuan-scott-xu reviewed
Thanks Chen! /lgtm

2022-08-30 17:01 UTC, chensun commented
/test kubeflow-pipelines-samples-v2

2022-08-30 18:44 UTC, chensun commented
/test kubeflow-pipelines-samples-v2

2022-08-30 20:05 UTC, chensun commented
/test kubeflow-pipelines-samples-v2

2022-08-30 20:27 UTC, connor-mccarthy commented
Reviewing this 👀

2022-08-30 20:50 UTC, connor-mccarthy requested changes
Thanks, @chensun. I think this there may be an idempotency issue or at least something I have a question about.

This implementation results in changing PipelineSpec when you reload the pipeline. Try appending the following to one of the pipeline files, running it, then inspecting the `one.yaml` and `two.yaml` files. They are different.

```python
if __name__ == '__main__':
    compiler.Compiler().compile(
        pipeline_func=my_pipeline,
        package_path='one.yaml')

    from kfp import components
    with open('one.yaml', 'r') as f:
        reloaded_pipeline = components.load_component_from_text(f.read())
    compiler.Compiler().compile(
        reloaded_pipeline, package_path='two.yaml')
```

I don't think this is desired, correct? Even if the underlying pipeline logic is itself correct. WDYT?

If I am correct, the read/write tests will be very helpful for validating correctness across a diversity of pipelines if you switch the `.pipelines.config.read` flag to `True`, plus make a few other changes (see this commit for the additional changes needed: https://github.com/connor-mccarthy/pipelines/commit/746d787277e396ebf27b2d484878c2c2eb4c4333). If I am not correct, we probably still want to use the read/write tests to validate correctness, but they will need more attention in order to do so.

2022-08-31 09:02 UTC, chensun commented
> 



> Thanks, @chensun. I think this there may be an idempotency issue or at least something I have a question about.
> 
> This implementation results in changing PipelineSpec when you reload the pipeline. Try appending the following to one of the pipeline files, running it, then inspecting the `one.yaml` and `two.yaml` files. They are different.
> 
> ```python
> if __name__ == '__main__':
>     compiler.Compiler().compile(
>         pipeline_func=my_pipeline,
>         package_path='one.yaml')
> 
>     from kfp import components
>     with open('one.yaml', 'r') as f:
>         reloaded_pipeline = components.load_component_from_text(f.read())
>     compiler.Compiler().compile(
>         reloaded_pipeline, package_path='two.yaml')
> ```
> 
> I don't think this is desired, correct? Even if the underlying pipeline logic is itself correct. WDYT?
> 
> If I am correct, the read/write tests will be very helpful for validating correctness across a diversity of pipelines if you switch the `.pipelines.config.read` flag to `True`, plus make a few other changes (see this commit for the additional changes needed: [connor-mccarthy@746d787](https://github.com/connor-mccarthy/pipelines/commit/746d787277e396ebf27b2d484878c2c2eb4c4333)). If I am not correct, we probably still want to use the read/write tests to validate correctness, but they will need more attention in order to do so.

That's a good point. Although the changed PipelineSpec is still correct, agree that it is ideal to maintain consistency across read and write. Made the change.

2022-08-31 12:05 UTC, chensun commented
All test passed. Merging this to unblock my next PR. 
@connor-mccarthy please feel free to add additional comments, I'll address them in a follow up PR if needed. Thanks!

2022-08-31 12:05 UTC, merged

2022-08-31 15:16 UTC, connor-mccarthy reviewed
This looks great, @chensun. Thank you for updating the tests!

/lgtm

2022-08-31 15:16 UTC, connor-mccarthy commented on sdk/python/kfp/components/yaml_component.py
> +    Artribute:
```suggestion
    Attributes:
```

2022-08-31 15:16 UTC, connor-mccarthy commented on sdk/python/kfp/components/structures.py
> +        if self.implementation.container is None:
👍🏻

2022-08-31 15:16 UTC, connor-mccarthy commented on sdk/python/kfp/compiler/pipeline_spec_builder.py
> +def create_pipeline_spec(
I like this change