fix(backend): add retry run in v2 api. Fixes #8735
kubeflow/pipelines pull request #8749
Opened 2023-01-24 00:40 UTC by Linchin

**Description of your changes:**
* Added retry run in v2 api proto
* Added support for retry run in v2 api in the backend
* Unit test

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2023-01-24 00:40 UTC, Linchin commented
/test all

2023-01-24 21:56 UTC, Linchin commented
/test kubeflow-pipeline-backend-test

2023-01-24 22:30 UTC, Linchin commented
/test all

2023-01-26 00:04 UTC, Linchin commented on backend/api/v2beta1/run.proto
> +     post: "/apis/v2beta1/experiments/{experiment_id}/runs/{run_id}:retry"
Hi @difince  thank you for bringing this up. This was changed by @gkcalat during his run status design. I think the reason to add `/experiments/{experiment_id}/` segment is to follow AIP. @gkcalat please correct me if I'm wrong.

2023-01-26 11:46 UTC, difince reviewed
Hi @Linchin 
https://github.com/kubeflow/pipelines/blob/874e3d3e9136bb16c59cfcf4a3680de40513451c/backend/api/v2beta1/swagger/run.swagger.json#L18-L21

I wonder what URL to use so that the experiment is not defined?

2023-02-03 21:32 UTC, gkcalat requested changes
Hi @Linchin ! Could you please rebase this on the master branch.

2023-02-08 09:36 UTC, difince commented on backend/api/v2beta1/run.proto
> +     post: "/apis/v2beta1/experiments/{experiment_id}/runs/{run_id}:retry"
can you elaborate on the benefits?

2023-03-02 21:39 UTC, closed without merging