fix(sdk): bump JsonSchema pinned version to next major version. Fixes #8648
kubeflow/pipelines pull request #8855
Opened 2023-02-15 17:38 UTC by lresende

**Description of your changes:**
Bump JsonSchema pinned version to next major version to allow the Kubeflow
Pipeline SDK to be installed with the latest JupyterLab that requires JsonSchema>=4.17.3

Fixes #8648 

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2023-02-15 17:43 UTC, connor-mccarthy requested changes
Thanks, @lresende.

Did you run the `pip-compile` command described on [this line](https://github.com/kubeflow/pipelines/pull/8855/files#diff-63a2db662374dbedfd8bcec50462e9460017527f7efc41d5f5b80ef702f179e3L3)? Sometimes this command has no effect, which is fine.

Could you also update the release notes in `./sdk/RELEASE.md` in a style similar to the other entries?

Once you complete the CLA, let's merge it!

2023-02-15 18:03 UTC, lresende commented
@connor-mccarthy thanks for the quick reply, I have run the `pip-compile` and updated the `RELEASE.md` and cla has been submitted for new e-mail.

2023-02-15 18:07 UTC, connor-mccarthy requested changes

2023-02-15 18:07 UTC, connor-mccarthy commented on sdk/python/requirements.txt
> +    #   pydantic
It looks like the `requirements.txt` was not affected by your particular change and that this is attributed to the version of Python.

Can you revert this change?

2023-02-15 18:07 UTC, connor-mccarthy commented on sdk/RELEASE.md
> +* fix(sdk): bump JsonSchema pinned version to next major version. Fixes [#8648](https://github.com/kubeflow/pipelines/issues/8648) [#8855](https://github.com/kubeflow/pipelines/pull/8855)
Sorry -- missed this the first time: could you change this to `chore(sdk)` in the release note and the PR title?

Can you also add the specific version change? E.g., "bump JsonSchema pinned version to >=3.0.1,<5"?

2023-02-15 18:49 UTC, connor-mccarthy requested changes

2023-02-15 18:49 UTC, connor-mccarthy commented on sdk/RELEASE.md
> +* chore(sdk): bump JsonSchema pinned version to next major version. Fixes [#8648](https://github.com/kubeflow/pipelines/issues/8648) [#8855](https://github.com/kubeflow/pipelines/pull/8855)
Can you also add the specific version here?

2023-02-15 19:29 UTC, lresende commented
@connor-mccarthy once we get this merged, how do we go about publishing a patch release for this?

2023-02-15 19:32 UTC, connor-mccarthy commented
/ok-to-test

2023-02-15 19:35 UTC, connor-mccarthy commented
> @connor-mccarthy once we get this merged, how do we go about publishing a patch release for this?

By default this will be included in the KFP SDK 1.8.19 release. Ideally we wait for a few more changes to accumulate before cutting a new release.

2023-02-15 22:11 UTC, merged

2023-02-17 19:09 UTC, connor-mccarthy commented
@lresende, [`1.8.19`](https://pypi.org/project/kfp/1.8.19/) is released