feature(backend): Add support for accelerator config
kubeflow/pipelines pull request #8932
Opened 2023-03-04 23:58 UTC by gkcalat

**Description of your changes:**

[PipelineSpec has](https://github.com/kubeflow/pipelines/blob/a4abf27df478ca9a970ea4e4083adcd231ddda7e/api/v2alpha1/pipeline_spec.proto#L705-L711) `AcceleratorConfig` that specifies `Type` and `Count` for accelerator resources limits.

This PR adds support in KFP backend for the following vendors:
1. `nvidia.com/gpu`
2. `amd.com/gpu`
3. `cloud-tpus.goocle.com/v2` and `cloud-tpus.goocle.com/v3`
4. Custom vendors specified by users. E.g. `gpu.intel.com/i915`, `fpga.intel.com/v2`, `gpu-vendor.example/example-gpu`, etc.

Besides, we support accelerator type strings that are present in samples. For example, `TPU_V3`, `tpu-v3`, `nvidia-tesla-a100`, `NVIDIA_TESLAT_A100`, etc.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2023-03-05 06:02 UTC, chensun requested changes
Generally speaking we should have test for new code, especially for new features. Secondly, should we do this together with the node selector part? WDYT?

2023-03-06 20:44 UTC, gkcalat commented on backend/src/v2/driver/driver.go
> +			case strings.Contains(temp, "nvidia"):
Synced offline. We decided to remove the custom type handling and limit the scope of this PR to `resource.limits`. `nodeSelector`  will need to be general and not limited to the scope of accelerator config.

2023-03-06 22:42 UTC, chensun approved these changes
/lgtm
/approve

Thanks for adding the unit test coverage.

2023-03-06 23:02 UTC, gkcalat commented
/retest

2023-03-06 23:52 UTC, gkcalat commented
/retest

2023-03-07 01:22 UTC, merged