fix(sdk): fixes module not found error for containerized python components. Fixes #8385
kubeflow/pipelines pull request #9157
Opened 2023-04-14 19:55 UTC by Mithil467

**Description of your changes:**
Prepends the `module_directory` to sys.path. `module_directory` is [WindowsPath](https://docs.python.org/3/library/pathlib.html#pathlib.WindowsPath) object on windows, hence casting to string as sys.path doesn't support pathlib objects.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2023-04-14 20:23 UTC, connor-mccarthy requested changes
Thanks, @Mithil467. This is great.

Could you sign the CLA?

Could you also add at least one representative test case for this specific bug to this test file? https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/component_test.py

2023-04-14 20:23 UTC, connor-mccarthy commented
Fixes #8385

2023-04-14 21:57 UTC, Mithil467 commented
@connor-mccarthy I have signed the CLA.
I have also added a new unit test, let me know if this is good enough.

2023-04-14 22:24 UTC, Mithil467 commented
@connor-mccarthy I have signed the CLA.
I have also added a new unit test, let me know if this is good enough.

2023-04-17 16:39 UTC, connor-mccarthy commented
/ok-to-test

2023-04-17 17:01 UTC, connor-mccarthy requested changes
Thanks, @Mithil467. This looks and works great.

You can ignore the `kubeflow-pipelines-sdk-execution-tests` failures. They are unrelated to your changes.

One request before we merge: could you add a release note about this fix to the "Current Version:  Bug fixes and other changes" of [sdk/RELEASE.md](https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md#bug-fixes-and-other-changes)?

2023-04-17 18:35 UTC, Mithil467 commented
Sounds good, thanks @connor-mccarthy

2023-04-17 18:37 UTC, connor-mccarthy commented
/lgtm
/approve

Thank you for this, @Mithil467! The community will benefit greatly from this fix.

2023-04-17 18:46 UTC, merged